type User {
  id: ID!
  email: String!
  displayName: String!
  avatar: String!
  friends(query: ListInput): UserList! # Resolve
  notifications(query: ListInput): NotificationList! #Resolve
  createdAt: Date!
}

type UserList implements List {
  cursor: String!
  users: [User]!
}