type Notification {
  id: ID!
  text: String!
  url: String!
  read: Boolean!
  type: NotificationType!
  createdAt: Date!
}

type NotificationList implements List {
  cursor: String!
  notifications: [Notification]!
}