type Story {
  id: ID!
  parent: Story # Resolve
  text: String!
  photos: [Photo]!
  owner: User # Resolve
  reaction: ReactionType # Resolve
  likes: Int!
  dislikes: Int!
  comments(listInput: ListInput): StoryList! # Resolve
  exposed: Exposed
  createdAt: Date!
}

type StoryList implements List {
  cursor: String!
  stories: [Story]!
}