
type Story {
  id: ID!
  text: String!
  photos: [Photo]!
  isOwner: Boolean!
  reaction: ReactionType # Resolve
  likes: Int!
  dislikes: Int!
  comments(query: ListInput): StoryList! # Resolve
  exposed: Exposed
  createdAt: Date!
}

type StoryList implements List {
  cursor: String!
  stories: [Story]!
}